version: '3'
services:

  postgres:
    container_name: sample-db
    build: 
      context: .
      dockerfile: ./postgres/Dockerfile
      args:
        - DB_LANG=ja_JP
    restart: always
    ports: 
      - "3306:3306"
    volumes:
      - ./postgres/init:/docker-entrypoint-initdb.d
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=ja_JP.UTF-8"

volumes:
  postgres: